BITNAMI_CHART = {'image': {'pullPolicy': 'IfNotPresent',
           'registry': 'docker.io',
           'repository': 'bitnami/odoo',
           'tag': '11.0.20190115'},
 'ingress': {'enabled': False,
             'hosts': [{'annotations': None,
                        'certManager': False,
                        'name': 'odoo.local',
                        'tls': False,
                        'tlsSecret': 'odoo.local-tls'}],
             'secrets': None},
 'livenessProbe': {'enabled': True,
                   'failureThreshold': 6,
                   'initialDelaySeconds': 300,
                   'periodSeconds': 30,
                   'successThreshold': 1,
                   'timeoutSeconds': 5},
 'odooEmail': 'user@example.com',
 'odooUsername': 'user@example.com',
 'persistence': {'accessMode': 'ReadWriteOnce', 'enabled': True, 'size': '8Gi'},
 'postgresql': {'persistence': {'accessMode': 'ReadWriteOnce',
                                'enabled': True,
                                'size': '8Gi'}},
 'readinessProbe': {'enabled': True,
                    'failureThreshold': 6,
                    'initialDelaySeconds': 30,
                    'periodSeconds': 10,
                    'successThreshold': 1,
                    'timeoutSeconds': 5},
 'resources': {'requests': {'cpu': '300m', 'memory': '512Mi'}},
 'service': {'externalTrafficPolicy': 'Cluster',
             'nodePort': '',
             'port': 80,
             'type': 'LoadBalancer'}}
